steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push Training Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t $_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest -f dockerfiles/train.dockerfile .
        docker push $_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push API Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t $_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest -f dockerfiles/api.dockerfile .
        docker push $_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Training'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Starting training job..."
        
        SA_EMAIL="project99-sa@$PROJECT_ID.iam.gserviceaccount.com"
        
        JOB_NAME=$$(gcloud ai custom-jobs create \
          --region=$_REGION \
          --display-name=train-$BUILD_ID \
          --worker-pool-spec=machine-type=n1-standard-4,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest \
          --service-account=$$SA_EMAIL \
          --format="value(name)")
        
        echo "Training job created: $$JOB_NAME"
        
        while true; do
          STATE=$$(gcloud ai custom-jobs describe $$JOB_NAME --region=$_REGION --format="value(state)")
          echo "Current Job state: $$STATE"
          if [ "$$STATE" = "JOB_STATE_SUCCEEDED" ]; then
            break
          elif [[ "$$STATE" =~ "FAILED" || "$$STATE" =~ "CANCELLED" ]]; then
            exit 1
          fi
          sleep 30
        done

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Model'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud ai models upload \
          --region=$_REGION \
          --display-name=dtu-model \
          --container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest \
          --container-ports=8000 \
          --artifact-uri=gs://dtu-mlops-group99-data/models/

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Endpoint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MODEL_ID=$$(gcloud ai models list --region=$_REGION --filter="displayName=dtu-model" --format="value(name)" --sort-by="~createTime" | head -n 1)
        
        DEPLOYED_ID="deployed-$BUILD_ID"
        
        gcloud ai endpoints deploy-model $_ENDPOINT_ID \
          --region=$_REGION \
          --model=$$MODEL_ID \
          --display-name=deployed-$BUILD_ID \
          --machine-type=n1-standard-2 \
          --deployed-model-id=$$DEPLOYED_ID \
          --traffic-split=$$DEPLOYED_ID=100

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s 

substitutions:
  _REGION: europe-west1
  _ENDPOINT_ID: '846555783666597888'