steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest', '-f', 'dockerfiles/train.dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build API Image'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest', '-f', 'dockerfiles/api.dockerfile', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Training'
    entrypoint: 'gcloud'
    args: [
      'ai', 'custom-jobs', 'create',
      '--region=$_REGION',
      '--display-name=train-$BUILD_ID',
      '--worker-pool-spec=machine-type=n1-standard-4,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Model'
    entrypoint: 'gcloud'
    args: [
      'ai', 'models', 'upload',
      '--region=$_REGION',
      '--display-name=dtu-model',
      '--container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest',
      '--container-ports=8000'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Endpoint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        MODEL_ID=$$(gcloud ai models list \
          --region=$_REGION \
          --filter="displayName=dtu-model" \
          --format="value(name)" \
          --sort-by="~createTime" \
          | head -n 1)
        
        if [ -z "$$MODEL_ID" ]; then
          echo "ERROR: No model found with display name 'dtu-model'"
          exit 1
        fi
        
        gcloud ai endpoints deploy-model $_ENDPOINT_ID \
          --region=$_REGION \
          --model=$$MODEL_ID \
          --display-name=deployed-model-$BUILD_ID \
          --machine-type=n1-standard-2 \
          --traffic-split=0=100

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _ENDPOINT_ID: '846555783666597888'
