steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest', '-f', 'dockerfiles/train.dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build API Image'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest', '-f', 'dockerfiles/api.dockerfile', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Training'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Starting training job..."
        JOB_NAME=$$(gcloud ai custom-jobs create \
          --region=$_REGION \
          --display-name=train-$BUILD_ID \
          --worker-pool-spec=machine-type=n1-standard-4,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest \
          --format="value(name)")
        
        echo "Training job created: $$JOB_NAME"
        echo "Waiting for training to complete..."
        
        # Poll until job completes
        while true; do
          STATE=$$(gcloud ai custom-jobs describe $$JOB_NAME --region=$_REGION --format="value(state)")
          echo "Job state: $$STATE"
          
          if [ "$$STATE" = "JOB_STATE_SUCCEEDED" ]; then
            echo "Training completed successfully!"
            break
          elif [ "$$STATE" = "JOB_STATE_FAILED" ] || [ "$$STATE" = "JOB_STATE_CANCELLED" ]; then
            echo "ERROR: Training failed with state: $$STATE"
            gcloud ai custom-jobs describe $$JOB_NAME --region=$_REGION
            exit 1
          fi
          
          sleep 30
        done
        
        # Verify model was uploaded to GCS
        echo "Verifying model exists in GCS..."
        if gsutil ls gs://dtu-mlops-group99-data/models/xgboost_model.json; then
          echo "Model found in GCS!"
        else
          echo "ERROR: Model not found in GCS after training completed"
          exit 1
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Model'
    entrypoint: 'gcloud'
    args: [
      'ai', 'models', 'upload',
      '--region=$_REGION',
      '--display-name=dtu-model',
      '--container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest',
      '--container-ports=8000'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Endpoint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        MODEL_ID=$$(gcloud ai models list \
          --region=$_REGION \
          --filter="displayName=dtu-model" \
          --format="value(name)" \
          --sort-by="~createTime" \
          | head -n 1)
        
        if [ -z "$$MODEL_ID" ]; then
          echo "ERROR: No model found with display name 'dtu-model'"
          exit 1
        fi
        
        gcloud ai endpoints deploy-model $_ENDPOINT_ID \
          --region=$_REGION \
          --model=$$MODEL_ID \
          --display-name=deployed-model-$BUILD_ID \
          --machine-type=n1-standard-2 \
          --traffic-split=0=100

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _ENDPOINT_ID: '846555783666597888'
