steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args: 
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:$BUILD_ID'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest'
      - '--cache-from'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:latest'
      - '-f'
      - 'dockerfiles/train.dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Training Image'
    args: ['push', '--all-tags', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build API Image'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:$BUILD_ID'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest'
      - '--cache-from'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:latest'
      - '-f'
      - 'dockerfiles/api.dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push API Image'
    args: ['push', '--all-tags', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend Image'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/frontend-image:$BUILD_ID'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/frontend-image:latest'
      - '--cache-from'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/frontend-image:latest'
      - '-f'
      - 'dockerfiles/frontend.dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend Image'
    args: ['push', '--all-tags', '$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/frontend-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Training'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Starting training job..."
        JOB_NAME=$$(gcloud ai custom-jobs create \
          --region=$_REGION \
          --display-name=train-$BUILD_ID \
          --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/train-image:$BUILD_ID \
          --format="value(name)")
        
        echo "Training job created: $$JOB_NAME"
        echo "Waiting for training to complete..."
        
        # Poll until job completes
        while true; do
          STATE=$$(gcloud ai custom-jobs describe $$JOB_NAME --region=$_REGION --format="value(state)")
          echo "Job state: $$STATE"
          
          if [ "$$STATE" = "JOB_STATE_SUCCEEDED" ]; then
            echo "Training completed successfully!"
            break
          elif [ "$$STATE" = "JOB_STATE_FAILED" ] || [ "$$STATE" = "JOB_STATE_CANCELLED" ]; then
            echo "ERROR: Training failed with state: $$STATE"
            gcloud ai custom-jobs describe $$JOB_NAME --region=$_REGION
            exit 1
          fi
          
          sleep 30
        done
        
        # Verify model was uploaded to GCS
        echo "Verifying model exists in GCS..."
        if gsutil ls gs://dtu-mlops-group99-data/models/xgboost_model.json; then
          echo "Model found in GCS!"
        else
          echo "ERROR: Model not found in GCS after training completed"
          exit 1
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Model'
    entrypoint: 'gcloud'
    args: [
      'ai', 'models', 'upload',
      '--region=$_REGION',
      '--display-name=dtu-model',
      '--container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/api-image:$BUILD_ID',
      '--container-ports=8000',
      '--container-health-route=/health',
      '--container-predict-route=/predict'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Endpoint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        # 1. Undeploy ALL existing models first to free up resources
        echo "Checking for existing models to undeploy..."
        EXISTING_MODELS=$$(gcloud ai endpoints describe $_ENDPOINT_ID --region=$_REGION --format="value(deployedModels.id)")
        
        if [ -n "$$EXISTING_MODELS" ]; then
          # Split by semicolon if multiple models
          IFS=';' read -ra MODEL_IDS <<< "$$EXISTING_MODELS"
          for model_id in "$${MODEL_IDS[@]}"; do
            echo "Undeploying existing model: $$model_id"
            gcloud ai endpoints undeploy-model $_ENDPOINT_ID \
              --region=$_REGION \
              --deployed-model-id=$$model_id
          done
        else
          echo "No existing models found."
        fi

        # 2. Get the new model ID
        MODEL_ID=$$(gcloud ai models list \
          --region=$_REGION \
          --filter="displayName=dtu-model" \
          --format="value(name)" \
          --sort-by="~createTime" \
          | head -n 1)
        
        if [ -z "$$MODEL_ID" ]; then
          echo "ERROR: No model found with display name 'dtu-model'"
          exit 1
        fi
        
        gcloud ai endpoints deploy-model $_ENDPOINT_ID \
          --region=$_REGION \
          --model=$$MODEL_ID \
          --display-name=deployed-model-$BUILD_ID \
          --machine-type=n1-standard-2 \
          --service-account=487762099723-compute@developer.gserviceaccount.com \
          --traffic-split=0=100

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dtu-mlops-frontend'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/dtu-mlops-images/frontend-image:$BUILD_ID'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--set-env-vars=BACKEND_URL=https://europe-west1-aiplatform.googleapis.com/v1/projects/$PROJECT_ID/locations/$_REGION/endpoints/$_ENDPOINT_ID'

  # Make Frontend publicly accessible
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Make Frontend Public'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'dtu-mlops-frontend'
      - '--region=$_REGION'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _ENDPOINT_ID: '846555783666597888'

timeout: 10800s
